vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.g.mapleader = "\\"
vim.g.markdown_recommended_style = 0

vim.opt.autoindent = true
vim.opt.backup = false
vim.opt.completeopt = "menu,menuone,noselect"
vim.opt.confirm = true
vim.opt.cursorline = true
vim.opt.expandtab = true
vim.opt.formatoptions = "jcroqlnt"
vim.opt.inccommand = "split"
vim.opt.laststatus = 3
vim.opt.mouse = "a"
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 4
vim.opt.shiftround = true
vim.opt.shiftwidth = 2
vim.opt.sidescrolloff = 8
vim.opt.signcolumn = "yes"
vim.opt.smartindent = true
vim.opt.tabstop = 2
vim.opt.termguicolors = true
vim.opt.winminwidth = 5
vim.opt.wrap = false
vim.opt.writebackup = false

vim.keymap.set("n", "<leader>wh", "<C-w>h", { noremap = true })
vim.keymap.set("n", "<leader>wl", "<C-w>l", { noremap = true })
